Repository niloysikdar/Get-Set-Go, pull requests merged in 2022-03, with the labels that each got.

#17 made the home page responsive
  index.html
  styles/index.css
Labels: JWOC, hard

#24 Added Food Section
  foods.html
  images/bkg3.jpg
  images/bkg4.jpg
  index.html
  styles/foods.css
  styles/index.css
Labels: JWOC, hard

#23 Added a location page
  index.html
  js/app.js
  js/location.js
  location.html
  styles/index.css
  styles/location.css
Labels: JWOC, hard

#32 Made the signup and sign in pages responsive
  styles/signin.css
  styles/signup.css
Labels: JWOC, hard

#33 Added some more information about food in the food section
  .vscode/settings.json
  foods.html
  styles/foods.css
Labels: JWOC, medium

#36 Updated Gallery Section
  js/gallery.js
Labels: JWOC, easy
